### PR TITLE
Various Kernal updates

### PR DESCRIPTION
**Pull request by FeralChild64**
Many small fixes and improvements - some highlights:

- RUN/STOP + RESTORE works now
- PAL/NTSC detection (code from Codebase64, probably much shorter than the original one)
- fixed cartridge startup; some utility cart even display something before crashing

All similarities over 3 bytes explained.

### CODE REVIEW

**Review by gardners — APPROVED** [review]
Looks fine to me.

**Comment by gardners** [comment]
Very exciting to see the continued work!

**Comment by FeralChild64** [comment]
Just some small improvements... unfortunately, one of my other hobbies also demands attention now :)

**Comment by gardners** [comment]
No worries, and understood.  It'll be here for you when you have time again.

Paul.

**Pull request merged**
